### ISSUE TITLE
Short meeting to discuss details with each others

### ISSUE THREAD

**Issue by DeronLee** [monstarlab-chengdu-product-factory/monstar-lab-store#1]

**Comment by DeronLee** [comment]
@woocool @chenqiuxia @zhumeisongsong

**Comment by zhumeisongsong** [comment]
11.10 2:00PM CST
topic:
1设计语言的控制（颜色 字体字号 link button input ）
2商品中心的4个Api设计（广告 列表 详情 下单）
3模块与路由

**Comment by DeronLee** [comment]
@zhumeisongsong 上面提到的三个问题都ok或者建立单独的issue了么？都ok的话我就把这个issue关了哦
