### ISSUE TITLE
真实体验”码市“，取其精华，祛其糟粕，提交我们自己的需求

### ISSUE THREAD

**Issue by PowerXuan** [monstarlab-chengdu-product-factory/monstar-lab-store#2]
- [ ] 平冢

- [x] 李宁川

- [ ] 叶飞

- [x] 宋竹梅

希望各位认真体验一下“码市：https://mart.coding.net/quote/step-1
然后比对以前的报价经验，提出你们理想的报价系统应该是怎样的，哪些我们可以学习，哪些我们能做的更好，最终的用户是你们，希望提出好的意见！
为了节省时间，请直接用以下账号登录：zhumeisongsong／／ 2222222

**Comment by zhumeisongsong** [comment]
第一步页面：商品列表希望是竖列表 有简单介绍 不要只有图标
详情页面: 不喜欢打勾勾，希望是button选中/不选中的状态
模块功能的属性分类是好的，希望沿用

**Comment by PowerXuan** [comment]
用例1: 客户说不清楚自己想做什么东西，把这个网站丢给他，让他勾选自己想要的，我们只需要按照这个需求来报价即可；
用例2: 客户准备了很全面的Excel或X mind的功能一览，但仍然需要我们手动计算每一项价格，整个流程不够智能

**Comment by DeronLee** [comment]
1. 感觉第一层选择了大的平台之后，第二页直接就写列表内容过于多了，个人还是倾向于再做一步选择。
2. 字体太小。估计是因为功能太多，勾选不方便。但是鼠标HOVER时的右侧说明感觉不错。
3. 直接让用户输入页面数量是很奇怪的一件事情。但是怎么解决我也没想好
4.最终结果虽然很简洁，但是要查看具体详情的时候看不到，比如时间和成本。而且应该有一个开发队伍的因素，比如高级后端和初级后端的价格肯定不一样。要快的就多给钱找高级的。不着急想要便宜的就可以找初级的这种。
5. 缺乏具体案例，最好是可以根据用户的选择给出一些比较具体的案例，以及案例的参考金额。
6. 如果出现我们没有写，用户又需要的功能怎么办？
暂时只想到这些 @PowerXuan

**Comment by DeronLee** [comment]
@PowerXuan 我觉得要收集小平和叶飞的反馈会需要等一年

**Comment by zhumeisongsong** [comment]
我还有补充的地方：
这个项目启动的目的是前端组件模块化后方便后续项目快速搭建，所以希望原型的语汇可以更好适应模块化的需要，而不是单单解决需求。

**Comment by DeronLee** [comment]
@zhumeisongsong 这一块具体要怎么做呢？能否详细说明一下？

**Comment by zhumeisongsong** [comment]
比如说，一个页面需要一个带cover的nomal_list ,在原型上表明一个nomal_list的图文比例，图片位置为左还是右。这就是一个符合模块语汇的组件。
比如说 ，订单切换是tab列表，tab列表是标准样式的 tab_tags+normal_list，我们就又封装了一个组件了。
到底在页面上，你是要tab_tags+swipe_slides,还是tab_tags+nomal_list更好？这是希望交互解决的重点。

**Comment by zhumeisongsong** [comment]
频繁变动的，有时效性的，高级定制的需求，不希望划入到组件化的内容，而是做为增值服务体现。高频出现的定制需求再按行业和业务场景单独组件化。比如说，我们有底层商城的模块，它可以用来搭建付费的视频网站，利用现有的模块复用，我们可以更关注视频网站的使用特性定制符合特性的组件，然后交互设计的重点就转移到核心业务上。所以，我觉得这次项目的重点，是顶端设计后对底层模块的构建，我的组件可以方便扩展么？可以用到普遍场景减少重复劳动么？

**Comment by DeronLee** [comment]
@zhumeisongsong 非常棒，这一块你需要先想清楚，然后给我们相关的人员做说明。
包括具体细节要如何做才好。利用这次项目让大家都体会到便利感吧

**Comment by PowerXuan** [comment]
感谢大家的意见，此task已经完成。
